apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nxqm29gp7-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:9437cab7180c60eac75362dd1baa4fefff7a8150@sha256:86cfb345eb278f4d7bd480a59d4c7487ea9ee6501d24be9a687425f338db838b
          name: container-image
